### ISSUE TITLE
Always/Partially displays no results

### ISSUE THREAD

**Issue by Jev1337** [thecarpetjasp/passfind#2]
There is a bug where it always shows no results. Perhaps outdated or the API changed.

I made a pull request #1 .

Thanks!

**Comment by thecarpetjasp** [comment]
> There is a bug where it always shows no results. Perhaps outdated or the API changed.
> 
> I made a pull request #1 .
> 
> Thanks!

Thank Jev. Appreciate you keeping this updated!

Most likely what you said, outdated API usage. I know the API changed a lot. Many users reported dissatisfaction from it. How's it all still working now?
